spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/balance-changer
    username: postgres
    password: Qwerty1234
    driver-class-name: org.postgresql.Driver
  liquibase:
    enabled: true
    change-log: classpath:db/db.changelog-master.yaml
  jpa:
    show-sql: true